# Generated by Django 4.0.4 on 2023-11-18 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_class_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='Lecturer',
            new_name='lecturer',
        ),
    ]
